export const ADD_DATA = "ADD_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART ";
export const REDUCE_ORDER_QUANTITY = "REDUCE_ORDER_QUANTITY";
export const FILTER_ORDERS = "FILTER_ORDERS";
export const EMPTY_CART = "EMPTY_CART";
